version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: MySQL_DB
    environment:
      MYSQL_DATABASE: LaravelDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: Redis_DB
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: